#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script.
#   (2) The Java home directory must be set to point to a Java installation.
#
#   Alternatively, the JVM_OPTS environment variable can be set if you
#   want to override the default JVM options (default is -Xmx64m
#   -XX:MaxPermSize=32m).
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls -ld "$PRG"
    link=$(expr "$PRG" : '.*-> \(.*\)$')
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=$(dirname "$PRG")"/$link"
    fi
done
SAVED="$(cd "$(dirname "$PRG")" && pwd)"
cd "$SAVED" || exit

APP_HOME=$(pwd -P) || exit

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

# Add default JVM options here
JVM_OPTS=$(echo "$DEFAULT_JVM_OPTS $JAVA_OPTS" | tr '\n' ' ')
eval set -- "$JVM_OPTS" -classpath .:gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain "$@"

exec java "$@"
